### ISSUE TITLE
该公众号暂时无法提供服务，请稍后再试

### ISSUE THREAD

**Issue by cosmo2097** [node-webot/weixin-robot#79]
https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=1413446944&version=15&lang=zh_CN
根据微信最新的策略，如果设置了noReply=true或者回复内容为空串时，res.body应该为空。
否则一直会出现“该公众号暂时无法提供服务，请稍后再试”。
对wechat-mp做如下修改后测试正常。

```
/**
 * dump reply as xml string
 */
Wechat.dump = function(reply) {
  if (reply.content === '') {
    return '';
  }
  return mp_xml.build(reply);
}
```

**Comment by limsgithub** [comment]
如果设置了noReply=true或者回复内容为空串时，res.body应该为空。
否则一直会出现“该公众号暂时无法提供服务，请稍后再试”。

请问下这是在哪里设置的啊？？？
